media:
  input: static/media
  output: /media
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/post'
    view:
      fields: [ title, draft, date ]
    fields:
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text